services:
  server:
    build:
      context: ./server
    container_name: streamhub-server
    env_file:
      - ./.env
    ports:
      - "8787:8787"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: streamhub-frontend
    env_file:
      - ./.env
    depends_on:
      - server
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN:-localhost}
